# Generated by Django 5.2.5 on 2025-09-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='authur',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='feature_image',
            new_name='featured_image',
        ),
    ]
